# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0005_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
