# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0006_profile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('graduated', models.NullBooleanField()),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('conentrations', models.CharField(blank=True, max_length=256)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('societies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprofile.Profile')),
            ],
        ),
    ]
