# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='month_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='month_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
