# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0008_auto_20160108_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year_to', '-month_to']},
        ),
        migrations.AlterField(
            model_name='education',
            name='month_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='month_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
