# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0010_auto_20160108_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
