# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0011_auto_20160109_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='timestamp',
            new_name='created',
        ),
    ]
