# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0013_auto_20160109_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='conentrations',
            new_name='concentrations',
        ),
    ]
