# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0015_auto_20160109_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='month_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
