# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151230_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='local',
            new_name='locale',
        ),
    ]
